/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tubesoop;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Benando
 */
public class Status extends javax.swing.JFrame {
        Connection con;
        Statement stat;
        ResultSet rs;
        String sql;
    /**
     * Creates new form Status
     */
    public Status() {
        initComponents();
        DbConn DB = new DbConn();
        DB.config();
        con = DB.con;
        stat = DB.stm;
        idData();
        showData();
        TxtKeterangan.setLineWrap(true);
        CbId.addActionListener (new ActionListener () {
            public void actionPerformed(ActionEvent e) {
                showData();
            }
        });
        
        
    }
    
 

    
    public void idData(){
        try {
        sql = "SELECT * FROM barang";
        rs = stat.executeQuery(sql);
        while (rs.next()) {
            String idB = rs.getString("id_barang");
            CbId.addItem(idB);
        }
        
    } catch (Exception e) {

        JOptionPane.showMessageDialog(null, e);
    }
    }
    
    public void showData(){
        try {
        String idBarang = CbId.getSelectedItem().toString();
        sql = "SELECT * FROM barang WHERE id_barang = '" + idBarang + "'";
        rs = stat.executeQuery(sql);
            while (rs.next()) {
                String nama = rs.getString("nama_barang");
                String Warna = rs.getString("warna_barang");
                String Deskrip = rs.getString("deskripsi");
              
                TxtNama.setText(nama);
                TxtWarna.setText(Warna);
                TxtKeterangan.setText(Deskrip);
            }
        
        } catch (Exception e) {
        }
    }
    
    public void Taken(){
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        CbId = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TxtWarna = new javax.swing.JTextField();
        TxtNama = new javax.swing.JTextField();
        BtnTaken = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxtKeterangan = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID Barang");

        CbId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbIdActionPerformed(evt);
            }
        });

        jLabel2.setText("Tipe Barang");

        jLabel3.setText("Warna Barang");

        jLabel4.setText("Keterangan Tambahan");

        TxtWarna.setEditable(false);

        TxtNama.setEditable(false);

        BtnTaken.setText("Telah Diambil");
        BtnTaken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTakenActionPerformed(evt);
            }
        });

        TxtKeterangan.setEditable(false);
        TxtKeterangan.setColumns(20);
        TxtKeterangan.setRows(5);
        jScrollPane1.setViewportView(TxtKeterangan);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(227, 227, 227)
                .addComponent(BtnTaken)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2))
                .addGap(141, 141, 141)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxtNama)
                    .addComponent(jScrollPane1)
                    .addComponent(CbId, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TxtWarna))
                .addGap(160, 160, 160))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(CbId, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TxtWarna, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(BtnTaken)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CbIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbIdActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_CbIdActionPerformed

    private void BtnTakenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTakenActionPerformed
        // TODO add your handling code here:
       try {
            String tID = CbId.getSelectedItem().toString();
            sql = "UPDATE barang SET status_barang 'T' "
                    + "WHERE id_barang = '" + tID + "'";
            stat.execute(sql);
            System.out.println("Berhasil update data");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_BtnTakenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Status.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Status.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Status.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Status.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Status().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnTaken;
    private javax.swing.JComboBox<String> CbId;
    private javax.swing.JTextArea TxtKeterangan;
    private javax.swing.JTextField TxtNama;
    private javax.swing.JTextField TxtWarna;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
